# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: currency
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/currencyservice/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: 'Archive Image'
      inputs:
        repository: currency
        command: save
        arguments: '--output $(Build.ArtifactStagingDirectory)/currency_$(tag).image.tar currency:$(tag)'
        addPipelineData: false
    - task: PublishPipelineArtifact@1
      displayName: 'Publishing Image as Pipeline Artifact'
      inputs:
        path: '$(Build.ArtifactStagingDirectory)'
        artifact: 'ContainerImage'

- stage: 'Dev'
  displayName: 'Deploy to Dev Environment'
  dependsOn: Build
  jobs:
  - deployment: currency-deploy-dev
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: Docker@2
            displayName: 'Load Image from Tar'
            inputs:
              command: load
              arguments: '--input $(Pipeline.Workspace)/ContainerImage/currency_$(tag).image.tar'
          - task: Docker@2
            displayName: 'Push Image to ACR'
            inputs:
              containerRegistry: DevContainer
              repository: currency
              command: push