# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  template: template/vars.yml
  tag: '$(Build.BuildId)'
  containerRegistryDev: 'testuim.azurecr.io'
  # containerRegistryQA: 'testuimqa.azurecr.io'
  # containerRegistryUAT: 'testuimuat.azurecr.io'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: payment
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/paymentservice/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: 'Archive Image'
      inputs:
        repository: payment
        command: save
        arguments: '--output $(Build.ArtifactStagingDirectory)/payment_$(tag).image.tar payment:$(tag)'
        addPipelineData: false
    - task: PublishPipelineArtifact@1
      displayName: 'Publishing Image as Pipeline Artifact'
      inputs:
        path: '$(Build.ArtifactStagingDirectory)'
        artifact: 'ContainerImage'

- stage: 'Dev'
  displayName: 'Deploy to Dev Environment'
  dependsOn: Build
  jobs:
  - deployment: payment_deploy_dev
    environment: dev
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: Docker@2
            displayName: 'Load Image from Tar'
            inputs:
              command: load
              arguments: '--input $(Pipeline.Workspace)/ContainerImage/payment_$(tag).image.tar'
          - task: Docker@2
            displayName: 'ReTag Image with ACR Name - BuildId'
            inputs:
              containerRegistry: DevContainer # This comes from the Service Connections
              repository: dev/payment
              command: tag
              arguments: 'payment:$(tag) ${{ variables.containerRegistryDev }}/dev/payment:$(tag)' 
          - task: Docker@2
            displayName: 'Push Image to ACR'
            inputs:
              containerRegistry: DevContainer
              repository: dev/payment
              command: push
              tags: $(tag)
              
- stage: 'QA'
  displayName: 'Deploy to Dev Environment'
  dependsOn: Dev
  jobs:
  - deployment: payment_deploy_qa
    environment: qa
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: Docker@2
            displayName: 'Load Image from Tar'
            inputs:
              command: load
              arguments: '--input $(Pipeline.Workspace)/ContainerImage/payment_$(tag).image.tar'
          - task: Docker@2
            displayName: 'ReTag Image with ACR Name - BuildId'
            inputs:
              containerRegistry: DevContainer # This comes from the Service Connections
              repository: qa/payment
              command: tag
              arguments: 'payment:$(tag) ${{ variables.containerRegistryDev }}/qa/payment:$(tag)' 
          - task: Docker@2
            displayName: 'Push Image to ACR'
            inputs:
              containerRegistry: DevContainer
              repository: qa/payment
              command: push
              tags: $(tag)
              
- stage: 'UAT'
  displayName: 'Deploy to Dev Environment'
  dependsOn: QA
  jobs:
   - deployment: payment_deploy_uat
     environment: uat
     pool:
      vmImage: ubuntu-latest
     strategy:
       runOnce:
         deploy:
          steps:
          - checkout: self
          - task: Docker@2
            displayName: 'Load Image from Tar'
            inputs:
              command: load
              arguments: '--input $(Pipeline.Workspace)/ContainerImage/payment_$(tag).image.tar'
          - task: Docker@2
            displayName: 'ReTag Image with ACR Name - BuildId'
            inputs:
              containerRegistry: UatContainer # This comes from the Service Connections
              repository: uat/payment
              command: tag
              arguments: 'payment:$(tag) ${{ variables.containerRegistryDev }}/uat/payment:$(tag)' 
              
          - task: Docker@2
            displayName: 'ReTag Image with ACR Name - latest'
            inputs:
              containerRegistry: DevContainer
              repository: uat/payment
              command: tag
              arguments: 'payment:$(tag) ${{ variables.containerRegistryDev }}/uat/payment:latest'
          - task: Docker@2
            displayName: 'Push Image to ACR'
            inputs:
              containerRegistry: DevContainer
              repository: uat/payment
              command: push
              tags: |
                $(tag)
                latest
