# Get the resources and all the images in the repo and their deployment order
parameters:
  name: services
  type: object
  default: ['currency', 'payment']

resources:
  containers:
  - container: currency
    type: ACR
    azureSubscription: SubServiceConnection
    resourceGroup: devops-test-rg
    registry: testuim
    repository: qa/currency
  - container: payment
    type: ACR
    azureSubscription: SubServiceConnection
    resourceGroup: devops-test-rg
    registry: testuim
    repository: qa/payment
# Deployment Steps as follows

# Download all the images and retag with maybe buildID & latest
variables:
- name: registry
  value:  $(resources.container.${{ service }}.registry)
- name: repository
  value:  $(resources.container.${{ service }}.repository)
- name: image_tag
  value: $(resources.container.${{ service }}.tag)
- name: containerRegistryURL
  value: acrt01.azurecr.io
# - name: repository
#   value: ${{ parameters.service }}

# Send the image to ACR03

stages:
- stage: 'Pull Latest to UAT ACR'
  jobs:
    - job: 'PullUAT'
      pool:
        vmImage: ubuntu-latest
      steps:
      - ${{ each service in parameters.services }}:
        - task: Docker@2
          displayName: 'Pull Image from QA ACR'
          inputs:
            command: pull
            argument: $(registry)/$(repository)/${{ service }}:$(image_tag)
        - task: Docker@2
          displayName: 'Retag Image'
          inputs:
            command: tag
            containerRegistry: ${{ variables.registry }}
            repository: ${{ variables.repository }}
            arguments: '${{ service }}:${{ variables.image_tag }} ${{ variables.containerRegistryURL }}/uat/${{ service }}:${{ variables.image_tag }}_rc'
        - task: Docker@2
          displayName: 'Retag Image'
          inputs:
            command: tag
            containerRegistry: ${{ variables.registry }}
            repository: ${{ variables.repository }}
            arguments: '${{ service }}:${{ variables.image_tag }} ${{ variables.containerRegistryURL }}/uat/${{ service }}:latest'
        - task: Docker@2
          displayName: 'Push Image to ACR'
          inputs:
            containerRegistry: acrt01
            repository: uat/${{ service }}
            command: push
            tags: |
              ${{ variables.image_tag }}_rc
              latest
# - stage: 'DeployService'
#   jobs:
#   - job: 'deployservice'
#     pool:
#       vmImage: ubuntu-latest
#     steps:
#     - ${{ each service in parameters.services }}:
#       # - task: HelmDeploy@0
#       #   inputs:
#       #     azureSubscription:
#       #     azureResourceGroup:
#       #     kubernetesCluster:
#       #     namespace:
#       #     chartType:
#       #     chartPath: $(Build.SourcesDirectory)/HUGO/${{ parameter.service }}_directory
#       #     valueFile:
#       #     releaseName: ${{ parameters.service }}
#       #     arguments: --set=env=${{ parameters.kubeNamespace }},image.repository=${{ parameters.service }},image.tag=$(resources.container.${{ parameters.service }}.tag)
#       - script: echo "Running ${{ service }} now"        
